wip: evolving tests
Refactored core test logic towards being able to run from uTest as well as Specs2
Moved it to 'shared' to ensure it builds in ScalaJs

Wrote tests same way in uTest but does not run

 -----
[jvm] $ +js/test
[info] Setting version to 2.11.2
[info] Set current project to jvm (in build file:/home/nickdsc/projects/playframework-learn/play-scalajs-showcase/)

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "sbt-web-scheduler-1"
[trace] Stack trace suppressed: run last js/test:test for the full output.
[error] Could not run test domain.TaskManagementSpecuTest: java.util.concurrent.ExecutionException: Boxed Error
[trace] Stack trace suppressed: run last js/test:executeTests for the full output.
[error] (js/test:executeTests) java.util.concurrent.ExecutionException: Boxed Error
[error] Total time: 335 s, completed Feb 2, 2015 7:08:23 PM
[jvm] $ last js/test:test
[debug] Running TaskDef(domain.TaskManagementSpecuTest, org.scalajs.testadapter.FingerprintSerializers$DeserializedSubclassFingerprint@79074081, false, [SuiteSelector])
java.util.concurrent.ExecutionException: Boxed Error
	at scala.concurrent.impl.Promise$.resolver(Promise.scala:55)
	at scala.concurrent.impl.Promise$.scala$concurrent$impl$Promise$$resolveTry(Promise.scala:47)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:244)
	at scala.concurrent.Promise$class.complete(Promise.scala:55)
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153)
	at scala.concurrent.Promise$class.failure(Promise.scala:107)
	at scala.concurrent.impl.Promise$DefaultPromise.failure(Promise.scala:153)
	at org.scalajs.jsenv.rhino.RhinoJSEnv$AsyncRunner$$anon$1.run(RhinoJSEnv.scala:80)
Caused by: java.lang.OutOfMemoryError: Java heap space

 -----

 Follow up on these:
 * https://github.com/lihaoyi/utest/issues/33#issuecomment-65055113

*  https://github.com/lihaoyi/utest/issues/42