checkpoint: migrate build to latest PlayScalaJS plugin
1 uTests are called.
Seems TestFramework must be used for 'client_js' project and nowhere else.

2. @JSExport works: see note on Task

3. Still getting some asserts from JVM tests...

Unclear if caused by a logical bug or concurrency

[info] 1 example, 0 failure, 0 error
java.lang.AssertionError: assertion failed
	at scala.Predef$.assert(Predef.scala:151)
	at shared.app.taskmgmt.proxy.TaskManagementModelProxy$$anonfun$1.applyOrElse(TaskManagementModelProxy.scala:88)
	at shared.app.taskmgmt.proxy.TaskManagementModelProxy$$anonfun$1.applyOrElse(TaskManagementModelProxy.scala:83)
	at scala.concurrent.Future$$anonfun$andThen$1.apply(Future.scala:434)
	at scala.concurrent.Future$$anonfun$andThen$1.apply(Future.scala:433)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.pollAndExecAll(ForkJoinPool.java:1253)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1346)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Cleared 1 tasks
Cleared 0 tasks
java.lang.AssertionError: assertion failed
	at scala.Predef$.assert(Predef.scala:151)
	at shared.app.taskmgmt.proxy.TaskManagementModelProxy$$anonfun$do_clearCompletedTasks$1.applyOrElse(TaskManagementModelProxy.scala:113)
	at shared.app.taskmgmt.proxy.TaskManagementModelProxy$$anonfun$do_clearCompletedTasks$1.applyOrElse(TaskManagementModelProxy.scala:106)
	at scala.concurrent.Future$$anonfun$andThen$1.apply(Future.scala:434)
	at scala.concurrent.Future$$anonfun$andThen$1.apply(Future.scala:433)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.pollAndExecAll(ForkJoinPool.java:1253)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1346)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
[info] TaskManagementSpec
[info]
[info] I should be able to should
[info] + schedule one task, redefine and complete it
[info] + schedule one task and cancel it
[info] + schedule one task and complete it remotely
[info] x schedule two tasks and complete them separately
[error]    Fixed now, you should remove the 'pendingUntilFixed' marker (TaskManagementSpec.scala:132)
[info]
[info]
[info] Total for specification TaskManagementSpec
[info] Finished in 75 ms
[info] 4 examples, 1 failure, 0 error
[error] Failed: Total 5, Failed 1, Errors 0, Passed 4
[error] Failed tests:
[error] 	showcase.tests.TaskManagementSpec
[error] (showcase_server/test:test) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 22 s, completed Feb 18, 2015 8:26:54 AM